[package]
name = "aurora"
version = "0.1.0"
authors = ["Euan Rochester <euan@rochester.me.uk>"]

[dependencies]
futures = "0.1.0"
tokio-core = "0.1.3"
tokio-proto = "0.1.0"
tokio-service = "0.1.0"
crc16 = "0.3.3"
byteorder = "1.0.0"

[[bin]]
doc = false
name = "main"
