enum_from_primitive! {
#[repr(u8)]
#[derive(Clone,Copy,Debug)]
pub enum MeasurementType{
    GridVoltage = 1,
    GridCurrent = 2,
    GridPower = 3,
    Frequency = 4,
    Vbulk = 5,
    IleakDc = 6,
    ILeakInverter = 7,
    Pin1 = 8,
    Pin2 = 9,
    InverterTemperature = 21,
    BoosterTemperature = 22,
    Input1Voltage = 23,
    Input1Current = 25,
    Input2Voltage = 26,
    Input2Current = 27,
    GridVoltageDc = 28,
    GridFrequencyDc = 29,
    IsolationResistance = 30,
    VbulkDc = 31,
    AverageGridVoltage = 32,
    VbulkMid = 33,
    PeakPower = 34,
    PeakPowerToday = 35,
    GridVoltageNeutral = 36,
    WindGeneratorFrequency = 37,
    GridVoltageNeutralPhase = 38,
    GridCurrentPhaseR = 39,
    GridCurrentPhaseS = 40,
    GridCurrentPhaseT = 41,
    FrequencyPhaseR = 42,
    FrequencyPhaseS = 43,
    FrequencyPhaseT = 44,
    VbulkPos = 45,
    VbulkNeg = 46,
    SupervisorTemp = 47,
    AlimTemp = 48,
    HeatSinkTemp = 49,
    Temp1 = 50,
    Temp2 = 51,
    Temp3 = 52,
    FanSpeed1 = 53,
    FanSpeed2 = 54,
    FanSpeed3 = 55,
    FanSpeed4 = 56,
    FanSpeed5 = 57,
    PowerSaturationLimit = 58,
    ReferenceRingBulk = 59,
    VpanelMicro = 60,
    GridVoltagePhaseR = 61,
    GridVoltagePhaseS = 62,
    GridVoltagePhaseT = 63,
}
}



enum_from_primitive! {
#[repr(u8)]
#[derive(Clone,Copy,Debug)]
pub enum TransmissionState{ 
    Ok = 0,
    CommandNotImplemented = 51,
    VariableDoesNotExist = 52,
    VariableValueOutOfRange = 53,
    EEpromNotAccessible = 54,
    NotToggledServiceMode = 55,
    CannotSendCommandToInternalMicro = 56,
    CommandNotExecuted = 57,
    VariableNotAvailableRetry = 58
}
}

enum_from_primitive! {
#[repr(u8)]
#[derive(Clone,Copy,Debug)]
pub enum GlobalState{ 
    SendingParameters=0,
    WaitSunOrGrid=1,
    CheckingGrid=2,
    MeasuringRiso=3,
    DcDcStart=4,
    InverterStart=5,
    Run=6,
    Recovery=7,
    Pause=8,
    GroundFault=9,
    OTHFault=10,
    AddressSetting=11,
    SelfTest=12,
    SelfTestFail=13,
    SensorTestAndMeasRiso=14,
    LeakFault=15,
    Waitingformanualreset=16,
    InternalErrorE026=17,
    InternalErrorE027=18,
    InternalErrorE028=19,
    InternalErrorE029=20,
    InternalErrorE030=21,
    SendingWindTable=22,
    FailedSendingtable=23,
    UTHFault=24,
    RemoteOFF=25,
    InterlockFail=26,
    ExecutingAutotest=27,
    WaitingSun=30,
    TemperatureFault=31,
    FanStaucked=32,
    IntComFault=33,
    SlaveInsertion=34,
    DCSwitchOpen=35,
    TRASSwitchOpen=36,
    MASTERExclusion=37,
    AutExclusion=38,
    ErasingInternalEeprom=98,
    ErasingExternalEeprom=99,
    CountingEeprom=100,
    Freeze=101,
}
}

enum_from_primitive! {
#[repr(u8)]
#[derive(Clone,Copy,Debug)]
pub enum DcDcState{
    DcDcOFF=0,
    RampStart=1,
    MPPT=2,
    NotUsed=3,
    InputOC=4,
    InputUV=5,
    InputOV=6,
    InputLow=7,
    NoParameters=8,
    BulkOV=9,
    CommunicationError=10,
    RampFail=11,
    InternalError=12,
    InputmodeError=13,
    GroundFault=14,
    InverterFail=15,
    DcDcIGBTSat=16,
    DcDcILEAKFail=17,
    DcDcGridFail=18,
    DcDcCommError=19,
}
}

enum_from_primitive! {
#[repr(u8)]
#[derive(Clone,Copy,Debug)]
pub enum InverterState{
    StandBy=0,
    CheckingGrid=1,
    Run=2,
    BulkOV=3,
    OutOC=4,
    IGBTSat=5,
    BulkUV=6,
    DegaussError=7,
    NoParameters=8,
    BulkLow=9,
    GridOV=10,
    CommunicationError=11,
    Degaussing=12,
    Starting=13,
    BulkCapFail=14,
    LeakFail=15,
    DcDcFail=16,
    IleakSensorFail=17,
    SelfTestRelayInverter=18,
    SelfTestWaitForSensorTest=19,
    SelfTestTestRelayDcDcAndSensor=20,
    SelfTestRelayInverterFail=21,
    SelfTestTimeoutFail=22,
    SelfTestRelayDcDcFail=23,
    SelfTest1=24,
    WaitingSelfTestStart=25,
    DcInjection=26,
    SelfTest2=27,
    SelfTest3=28,
    SelfTest4=29,
    InternalError=30,
    InternalError2=31,
    ForbiddenState=40,
    InputUC=41,
    ZeroPower=42,
    GridNotPresent=43,
    WaitingStart=44,
    MPPT=45,
    GridFail=46,
    InputOC=47,
}
}
